### ISSUE TITLE
Wireframe image should be in the readme

### ISSUE THREAD

**Issue by gittheking** [echerney/escaping-shia#2]
@echerney  Your wireframe jpg isn't viewable in it's current form. Please resubmit in a different format or include it in your readme markdown. Here's a nice little markdown cheatsheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by echerney** [comment]
Hey Bobby, sorry about that. It's up now. The basic idea I have is pretty
simple but I have some ideas about how to make it more interesting and fun,
although I'm not sure how much of it is practical.

Thanks,
Erin

**Comment by gittheking** [comment]
@echerney - No problem, looks good. In the future, clean up your user stories to account for _every_ feature. http://www.agilemodeling.com/artifacts/userStory.htm 
👍
